'use strict';

module.exports = {
  async up(queryInterface) {
    await queryInterface.bulkInsert('menu_items', [
      {
        name: 'Margherita Pizza',
        description: 'Classic pizza with fresh mozzarella, tomato sauce, and basil leaves on a thin, crispy crust.',
        price: 12.99,
        image: 'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=400',
        category: 'pizza',
        is_available: true,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: 'Pepperoni Supreme',
        description: 'Loaded with double pepperoni, mozzarella cheese, and our signature spicy tomato sauce.',
        price: 15.99,
        image: 'https://images.unsplash.com/photo-1628840042765-356cda07504e?w=400',
        category: 'pizza',
        is_available: true,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: 'BBQ Chicken Pizza',
        description: 'Smoky BBQ sauce, grilled chicken, red onions, cilantro, and smoked gouda cheese.',
        price: 16.99,
        image: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=400',
        category: 'pizza',
        is_available: true,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: 'Classic Smash Burger',
        description: 'Double smashed beef patties, American cheese, pickles, onions, and special sauce on a brioche bun.',
        price: 11.49,
        image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=400',
        category: 'burger',
        is_available: true,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: 'Spicy Jalapeño Burger',
        description: 'Angus beef patty with pepper jack cheese, crispy jalapeños, chipotle mayo, and fresh lettuce.',
        price: 13.99,
        image: 'https://images.unsplash.com/photo-1553979459-d2229ba7433b?w=400',
        category: 'burger',
        is_available: true,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: 'Mushroom Swiss Burger',
        description: 'Juicy beef patty topped with sautéed mushrooms, melted Swiss cheese, and truffle aioli.',
        price: 14.49,
        image: 'https://images.unsplash.com/photo-1572802419224-296b0aeee0d9?w=400',
        category: 'burger',
        is_available: true,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: 'Mango Smoothie',
        description: 'Fresh mango blended with yogurt, honey, and ice for a refreshing tropical treat.',
        price: 5.99,
        image: 'https://images.unsplash.com/photo-1623065422902-30a2d299bbe4?w=400',
        category: 'drink',
        is_available: true,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: 'Classic Lemonade',
        description: 'Freshly squeezed lemons with a hint of mint and just the right amount of sweetness.',
        price: 3.99,
        image: 'https://images.unsplash.com/photo-1621263764928-df1444c5e859?w=400',
        category: 'drink',
        is_available: true,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: 'Chocolate Lava Cake',
        description: 'Warm chocolate cake with a molten center, served with vanilla ice cream and fresh berries.',
        price: 8.99,
        image: 'https://images.unsplash.com/photo-1624353365286-3f8d62daad51?w=400',
        category: 'dessert',
        is_available: true,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: 'New York Cheesecake',
        description: 'Creamy cheesecake on a graham cracker crust with a strawberry compote drizzle.',
        price: 7.99,
        image: 'https://images.unsplash.com/photo-1533134242443-d4fd215305ad?w=400',
        category: 'dessert',
        is_available: true,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: 'Garlic Parmesan Fries',
        description: 'Crispy golden fries tossed in garlic butter and freshly grated Parmesan cheese.',
        price: 5.49,
        image: 'https://images.unsplash.com/photo-1573080496219-bb080dd4f877?w=400',
        category: 'side',
        is_available: true,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: 'Onion Rings',
        description: 'Beer-battered crispy onion rings served with smoky chipotle dipping sauce.',
        price: 4.99,
        image: 'https://images.unsplash.com/photo-1639024471283-03518883512d?w=400',
        category: 'side',
        is_available: true,
        created_at: new Date(),
        updated_at: new Date(),
      },
    ]);
  },

  async down(queryInterface) {
    await queryInterface.bulkDelete('menu_items', null, {});
  },
};
